---
title: "Sampling"
author: "Haolilan"
date: "2020/12/25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,echo=TRUE,warning=FALSE,rows.print =8)

# set directory
indir  <- "./metadata/"
outdir <- "./result/" 

# function
source("./scripts/SUMMARY_GITHUB_function.R")

```

```{r input, include = FALSE}
phen <- read.csv(paste0(indir,"/phenotype.vision2.csv"),header = T,stringsAsFactors = F) 
phen$Sites     <- factor(phen$Sites     ,levels = c("Tongue.coat","Buccal.mucosa","Feces","Vagina"))
phen$group_new <- factor(phen$group_new ,levels = c("B2","B1","B0","O1","O2","O3","O4","O5","W1","W2" ))
phen.va <- phen %>% subset(Sites == "Vagina")
```

### SAMPLING SUMMARY

```{r timepoints & dose }
##### capsule time, dose & menstrual related to FIG1 #####
## table ##
phen.caps.stat <- phen %>% subset(!is.na(group_new))
Cap.time <-
  data.frame(cbind(
    aggregate(
      phen.caps.stat$capsule_time,
      by = list(phen.caps.stat$group_new, phen.caps.stat$Sites),
      mean
    ),
    aggregate(
      phen.caps.stat$capsule_time,
      by = list(phen.caps.stat$group_new, phen.caps.stat$Sites),
      sd
    )
  )) %>% select(Group.1, Group.2, x, x.1)

names(Cap.time) <-
  c("group_new", "Sites", "mean", "sd")
Cap.time$type <- rep("capsule time", nrow(Cap.time))
Qua.cap <-
  data.frame(cbind(
    aggregate(
      phen.caps.stat$Quantity_of_capsule,
      by = list(phen.caps.stat$group_new, phen.caps.stat$Sites),
      mean
    ),
    aggregate(
      phen.caps.stat$Quantity_of_capsule,
      by = list(phen.caps.stat$group_new, phen.caps.stat$Sites),
      sd
    )
  )) %>% select(Group.1, Group.2, x, x.1)

names(Qua.cap) <-
  c("group_new", "Sites", "mean", "sd")
Qua.cap$type <- rep("Quantity of capsule", nrow(Qua.cap))
Men.last <-
  data.frame(cbind(
    aggregate(
      phen.caps.stat$day_lmp,
      by = list(phen.caps.stat$group_new, phen.caps.stat$Sites),
      mean,
      na.rm = TRUE
    ),
    aggregate(
      phen.caps.stat$day_lmp,
      by = list(phen.caps.stat$group_new, phen.caps.stat$Sites),
      sd,
      na.rm = TRUE
    )
  )) %>% select(Group.1, Group.2, x, x.1)

names(Men.last) <-
  c("group_new", "Sites", "mean", "sd")
Men.last$type <- rep("Last menstrual period", nrow(Men.last))
stat.group <- rbind(Cap.time, Qua.cap, Men.last)
stat.group <-
  stat.group %>% mutate(label = paste0(round(stat.group$mean, 0), " ± ", round(stat.group$sd, 0)))
stat.table <-
  arrange(data.frame(
    dcast(
      stat.group,
      Sites + type ~ group_new,
      value.var = "label",
      fun.aggregate = toString
    )
  ), type, Sites)
write.table(
  stat.table,
  paste0(outdir, "phenotype.cap_men.txt"),
  quote = F,
  row.names = F,
  sep = "\t"
)

## draw ##
phen.caps <-
  subset(phen, Sites == "Vagina" &
           !is.na(group_new)) %>% select(SeqID,
                                         SubjectID,
                                         group_new,
                                         capsule_time,
                                         Quantity_of_capsule,
                                         day_lmp)
phen.caps$group_new <-
  factor(phen.caps$group_new,
         levels = c("B2", "B1", "B0", "O1", "O2", "O3", "O4", "O5", "W1", "W2"))
col.group.new <-
  c(brewer.pal(5, "Blues")[c(2, 3, 5)],
    brewer.pal(9, "Oranges")[c(3, 5, 7, 9, 6, 4)],
    brewer.pal(9, "Greens")[c(4, 9)])
ggarrange(
  ## plot1
  ggplot(phen.caps, aes(
    x = group_new, y = capsule_time, color = group_new
  )) + scale_y_continuous(breaks = c(-300, 0, 30, 60, 90, 120, 150, 180, 210)) +
    labs(y = "", x = "") +
    geom_boxplot() + scale_color_manual(values = col.group.new) + coord_flip() +
    theme_light() + theme(
      panel.grid = element_blank(),
      axis.ticks = element_blank(),
      axis.text = element_blank()
    ),
  
  NULL,
  
  ## plot2
  ggplot(
    phen.caps,
    aes(x = capsule_time, y = Quantity_of_capsule, color = group_new)
  )   + scale_x_continuous(breaks = c(-300, 0, 30, 60, 90, 120, 150, 180, 210)) +
    scale_y_continuous(breaks = c(0, 7, 14, 28)) +
    geom_point(
      position = position_jitterdodge(),
      alpha = 0.7,
      size = 2
    ) + theme_light() + theme(axis.ticks = element_blank(), axis.text.x = element_blank()) +
    scale_color_manual(values = col.group.new) +
    labs(y = "Quantity of capsule", x = ""),
  
  ## plot3
  ggplot(
    phen.caps,
    aes(x = group_new, y = Quantity_of_capsule, color = group_new)
  )  + scale_y_continuous(breaks = c(0, 7, 14, 28)) + labs(y = "", x = "") +
    geom_boxplot() + geom_point(
      position = position_jitterdodge(jitter.width = 3),
      alpha = 0.5,
      size = 0.5
    ) + scale_color_manual(values = col.group.new) +
    theme_light() + theme(
      panel.grid = element_blank(),
      axis.ticks = element_blank(),
      axis.text = element_blank()
    ) ,
  
  ## plot4
  ggplot(
    phen.caps,
    aes(x = capsule_time, y = day_lmp, color = group_new)
  )   + scale_x_continuous(breaks = c(-300, 0, 30, 60, 90, 120, 150, 180, 210)) +
    scale_y_continuous(breaks = c(0, 7, 14, 28)) +
    geom_point(
      position = position_jitterdodge(),
      alpha = 0.7,
      size = 2
    ) + theme_light() + scale_color_manual(values = col.group.new) +
    labs(y = "Menstrual cycle(day)", x = "Sampling time(day)"),
  
  ## plot5
  ggplot(
    phen.caps,
    aes(x = group_new, y = day_lmp, color = group_new)
  )  + scale_y_continuous(breaks = c(0, 7, 14, 28)) + labs(y = "", x = "") +
    geom_boxplot() + geom_point(
      position = position_jitterdodge(jitter.width = 3),
      alpha = 0.5,
      size = 0.5
    ) + scale_color_manual(values = col.group.new) +
    theme_light() + theme(
      panel.grid = element_blank(),
      axis.ticks = element_blank(),
      axis.text = element_blank()
    ),
  common.legend = T,
  align = "v",
  ncol = 2,
  nrow = 3,
  legend = "right",
  widths = c(3, 1),
  heights = c(1, 3, 3.2)
)

```


```{r sampling time}
###### SFIG1 sampling pie plots ##############################################
phen <- phen %>% mutate(KitID = paste(SubjectID,Samtime))
phen.stat <- phen.va %>% mutate(Vagina = 1) %>% 
  mutate(KitID = paste(SubjectID,Samtime)) %>%
  mutate(Feces = ifelse(KitID %in% as.vector( phen$KitID[phen$Sites == "Feces"]), 1, 0)) %>%
  mutate(Buccal.mucosa = ifelse(KitID %in% as.vector(phen$KitID[phen$Sites == "Buccal.mucosa"]), 1, 0)) %>%
  mutate(Tongue.coat = ifelse(KitID %in% as.vector(phen$KitID[phen$Sites == "Tongue.coat"]), 1, 0))
data_graph <-
  select(phen.stat, group_by_time, SubjectID, Tongue.coat, Buccal.mucosa, Feces, Vagina)
data_graph <-
  melt(
    data_graph,
    id.vars = c("group_by_time", "SubjectID"),
    variable.name = "group",
    value.name = "nb"
  )
names(data_graph) <- c("x", "y", "group", "nb")
# make group a factor
data_graph$group <- factor(data_graph$group)
data_graph$y <-
  factor(data_graph$y, levels = rev(as.vector(arrange(
    data.frame(table(data_graph$y)), -Freq
  )$Var1)))
# separates the four pies
data_graph <-
  cbind(data_graph, case = paste0(data_graph$y, data_graph$x))
# calculate the start and end angles for each pie
data_graph <- left_join(data_graph,
                        data_graph %>%
                          group_by(case) %>%
                          summarize(nb_total = sum(nb))) %>%
  group_by(case) %>%
  mutate(nb_frac = 2 * pi * cumsum(nb) / nb_total,
         start = lag(nb_frac, default = 0))
# position of the labels
data_labels <- data_graph %>%
  group_by(case) %>%
  summarize(x = x[1], y = y[1], nb_total = nb_total[1])
# overall scaling for pie size
scale = .5 / sqrt(max(data_graph$nb_total))
# draw the pies
xlabels <-  c("-309",  "-45", "0",  "7", "14","30",  "60", "90", "120",  "150", "180",  "210", "240")
ylabels <- levels(data_graph$y)
data_graph$x <- as.numeric(data_graph$x) / 2
data_graph$y <- 2 * as.numeric(data_graph$y)
ggplot(data_graph) +
  geom_arc_bar(aes(
    x0 = x,
    y0 = y,
    r0 = 0,
    r = 0.98,
    start = start,
    end = nb_frac,
    fill = group
  ),
  color = "transparent") +
  scale_fill_brewer(
    '',
    palette = 'Set1',
    breaks = levels(data_graph$group),
    labels = c("Tongue coat coat", "Buccal mucosa", "Feces", "Vagina")
  ) +
  scale_x_continuous(
    breaks = c(-35, -15, 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100) / 2,
    labels = xlabels,
    name = "Sampling Time (days)"
  ) +
  scale_y_continuous(breaks = 2 * seq(1, length(ylabels)),
                     labels = ylabels,
                     name = "Subject ID") +
  theme_test() +
  theme(panel.grid.minor = element_blank(),
        legend.position = c(0.85, 0.1))
```