---
title: "INDIVIDUALS"
author: "Haolilan"
date: "2020/12/25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,echo=TRUE,warning=FALSE,rows.print =8,fig.width = 20,fig.height = 10)
setwd("E:/OneDrive - BGI Tech Solutions (Hongkong) Co., Ltd/intervene1211/common/GithubProbioticIntervention/Rscripts/rmd/")
# set directory
indir  <- "./metadata/"
outdir <- "./result/" 

# function
source("./scripts/SUMMARY_GITHUB_function.R")

```

```{r input, include = FALSE}
phen <- read.csv(paste0(indir,"/phenotype.vision2.csv"),header = T)
phen$Sites     <- factor(phen$Sites     ,levels = c("Tongue.coat","Buccal.mucosa","Feces","Vagina"))
phen$group_new <- factor(phen$group_new,levels = c("B2","B1","B0","O1","O2","O3","O4","O5","W1","W2" ))
## add new phenotype ##
median.sub <-
  read.csv(paste0(outdir,"/classifier/train.subject.csv"), header = T)
pret.sample <-
  read.table(
    paste0(outdir,"/classifier/intervene.train_pret_probability_all_436.group.txt"),
    header = T
  )
CST <- read.table(paste0(outdir,"/CST.436.samples.txt"),header = T) 
phen <- phen %>%
  mutate(group.median = median.sub$group.sub[match(SubjectID, median.sub$SubjectID)],
         group.pret   = pret.sample$group.pret[match(SeqID, pret.sample$SeqID)],
         CST.sam      = CST$CST[match(SeqID,CST$SeqID)]) %>%
  mutate(group.median = ifelse(is.na(group.median), "unclassified", as.vector(group.median)))
phen.va    <- phen %>% 
  subset(Sites == "Vagina") #%>% subset(!is.na(group_new))

### 01 species.pro
species.pro <- read.table(paste0(indir,"species.txt"),header = T)  
species.pro <- species.pro %>%  column_to_rownames("tax")  %>% 
  dplyr::select(as.vector(phen$SeqID)) %>% .[rowSums(.) != 0 ,]

### 02 genus.pro / lactobacillus .spp
genus.pro <- read.table(paste0(indir,"genus.txt"),header = T)  
genus.pro <- genus.pro %>%  column_to_rownames("tax")  %>% 
  dplyr::select(as.vector(phen$SeqID)) %>% .[rowSums(.) != 0 ,] 

###
data.hpv  <- read.table(paste0(indir,"hpv.intervene.txt"),header = T) 

```

# FOR INDIVIDUALS

```{r INDIVIDUALS & life-report}
##  INDIVIDUALS & life-report #####
phen.va <- subset(phen, Sites == "Vagina")
species.pro$tax <- rownames(species.pro)
dat <-
  melt( 
    species.pro,
    id.vars = "tax" ,
    variable.name = "SeqID",
    value.name = "Abundance"
  ) %>%
  mutate(tax = str_split_fixed(tax, "s__", 2)[, 2])
dat <- merge(dat, phen.va, by = "SeqID", all.y = T)
dat <- dat %>%
  mutate(
    pH = ifelse(
      pH %in% c("5", "5.1" , "5.3" , "5.5", "5.8", "7"),
      "7",
      ifelse(
        pH %in% c("4.5" , "4.7" , "4.8"),
        "4.8",
        ifelse(pH %in% c("4.2", "4.4"), "4.4", "4")
      )
    ),
    day_lmp_m = ifelse(
      day_lmp <= 7,
      "S1",
      ifelse(
        day_lmp <= 14,
        "S2",
        ifelse(day_lmp <= 21, "S3", "S4")
      )
    )
  ) #NA
sub.list <- c("S013","S020","S030","S065","S025")
for (i in sub.list) {
  samp.ID <- i
  ## all tax & order ##
  dat.sites <- subset(dat, Sites == "Vagina")
  tax.all <-
    arrange(aggregate(dat.sites$Abundance, by = list(as.vector(
      factor(dat.sites$tax)
    )), mean), -x) %>% subset(x != 0)
  #dat.sites$tax <- factor(dat.sites$tax,levels = tax.all$Group.1)
  tax.all <- c(tax.all$Group.1, "Others")
  
  ## one subject tax & order ##
  dat.draw <-
    subset(dat.sites, SubjectID %in% samp.ID) %>% subset(Abundance != 0)
  dat.draw$Samtime <- factor(as.vector(dat.draw$Samtime))
  dat.draw$tax <-
    ifelse(dat.draw$Abundance < 0.5, "Others", as.vector(dat.draw$tax)) #%>% ###0.5%
  dat.draw$tax <-
    factor(dat.draw$tax, levels = tax.all[sort(match(levels(factor(dat.draw$tax)), tax.all))])
  tax.draw  <- levels(factor(dat.draw$tax))
  
  ## COLOR ##
  cbPalette <-
    c(
      brewer.pal(8, "Set2"),
      brewer.pal(8, "Set1"),
      brewer.pal(8, "Set3"),
      brewer.pal(8, "Pastel2"),
      brewer.pal(8, "Pastel1"),
      colorRampPalette(c(
        "lightblue", "lightgreen", "lightpink", "grey60"
      ))(length(tax.all) - 40)
    )
  cbPalette_p1 <- cbPalette[match(tax.draw, tax.all)]
  
  ## bar plot ##
  p1 <-
    ggplot(dat.draw, aes(x = Samtime, y = Abundance, fill = tax)) +
    geom_bar(stat = "identity", position = "fill") +
    scale_fill_manual(values = cbPalette_p1, guide = guide_legend(ncol = 1)) +
    labs(title = samp.ID,
         fill = "Taxa",
         size = 10) + xlab("") + ylab("Relative Abundance") +
    theme_light() + theme(
      axis.title.x = element_blank(),
      axis.text.x = element_blank(),
      axis.ticks = element_blank()
    )
  p1
  
  
  ## note draw ##
  note.draw <-
    dplyr::select(
      dat.draw,
      capsule_time,
      SubjectID,
      SeqID,
      Quantity_of_capsule,
      Samtime,
      pH,
      Sensation_change,
      Sexual_intercourse_24h,
      Vaginal_douching_1M,
      Herbal_medicine_or_others_1M,
      CST.sam,
      day_lmp_m
    )
  note.draw <- note.draw[!duplicated(note.draw), ]
  
  ##Quantity##
  note.draw$phenotype <- rep("Quantity", nrow(note.draw))
  note.draw$capsule_time <- round(note.draw$capsule_time / 30, 1)
  ##menstruation## day_lmp
  data.mens <- note.draw %>%
    mutate(phenotype    = rep("Menstruation", nrow(note.draw)))
  
  ##pH##
  data.ph <- note.draw %>%
    mutate(phenotype    = rep("pH", nrow(note.draw)))
  data.ph  <- data.ph[!is.na(data.ph$pH),]
  data.ph$pH <- as.vector(factor(data.ph$pH))
  
  ##sen##
  data.sen <- note.draw %>%
    mutate(phenotype    = rep("Sensation_change", nrow(note.draw)))
  data.sen  <- data.sen[!is.na(data.sen$Sensation_change),]
  
  ##sex##
  data.sex <- note.draw %>%
    mutate(phenotype    = rep("Sexual_intercourse_24h", nrow(note.draw)))
  data.sex[grep(pattern = "N", data.sex$Sexual_intercourse_24h), "Sexual_intercourse_24h"] <-
    NA
  data.sex  <- data.sex[!is.na(data.sex$Sexual_intercourse_24h),]
  
  ##douching##
  data.douching <- note.draw %>%
    mutate(phenotype    = rep("Vaginal_douching_1M", nrow(note.draw)))
  data.douching[grep(pattern = "N", data.douching$Vaginal_douching_1M), "Vaginal_douching_1M"] <-
    NA
  data.douching  <-
    data.douching[!is.na(data.douching$Vaginal_douching_1M),]
  
  ##medicine##
  data.med <- note.draw %>%
    mutate(phenotype    = rep("Herbal_medicine_or_others_1M", nrow(note.draw)))
  data.med[grep(pattern = "N", data.med$Herbal_medicine_or_others_1M), "Herbal_medicine_or_others_1M"] <-
    NA
  data.med  <-
    data.med[!is.na(data.med$Herbal_medicine_or_others_1M),]
  
  ##
  data.cst <- note.draw %>%
    mutate(phenotype    = rep("CST", nrow(note.draw)))
  
  ##
  data.capsuletime <- note.draw %>%
    mutate(phenotype    = rep("capsule_time/M", nrow(note.draw)))
  
  ##
  cst.set      <- as.numeric(levels(factor(dat.draw$CST.sam)))
  cbPalette_v2 <- brewer.pal(8, "Set1")[cst.set]
  p2 <-
    ggplot(note.draw, aes(
      x = Samtime,
      y = phenotype,
      color = as.factor(CST.sam)
    )) +
    geom_point(data = data.cst,
               size = 4,
               shape = 15) +
    scale_color_manual(values = cbPalette_v2, guide = guide_legend(ncol = 1, )) +
    labs(color = "") +
    theme_pubclean() + theme(
      axis.title = element_blank(),
      axis.text.x = element_blank(),
      axis.ticks = element_blank(),
      legend.position = "right",
      panel.background = element_rect(fill = "transparent", colour = NA),
      legend.background = element_rect(fill = "transparent", colour = NA),
      plot.background = element_rect(fill = "transparent", colour = NA)
    )
  ####
  fac.all <-
    c(
      levels(factor(dat$Sensation_change)),
      levels(factor(dat$pH)),
      levels(factor(dat$Herbal_medicine_or_others_1M)),
      levels(factor(dat$Sexual_intercourse_24h)),
      levels(factor(dat$Vaginal_douching_1M)),
      levels(factor(dat$day_lmp_m))
    )
  fac.note1 <- levels(factor(note.draw$Sensation_change))
  fac.note2 <- levels(factor(note.draw$pH))
  fac.note3 <-
    levels(factor(note.draw$Herbal_medicine_or_others_1M))
  fac.note4 <- levels(factor(note.draw$Sexual_intercourse_24h))
  fac.note5 <- levels(factor(note.draw$Vaginal_douching_1M))
  fac.note6 <- levels(factor(note.draw$day_lmp_m))
  #
  cbPalette_v3 <- c(brewer.pal(12, "Paired"), brewer.pal(3, "Pastel2"))
  cbPalette_v4 <- c(
    cbPalette_v3[match(fac.note1, fac.all)],
    cbPalette_v3[match(fac.note2, fac.all)],
    cbPalette_v3[match(fac.note3, fac.all[1:10])],
    cbPalette_v3[match(fac.note4, fac.all[11:12]) + 10],
    cbPalette_v3[match(fac.note5, fac.all[13:14]) + 12],
    cbPalette_v3[match(fac.note6, fac.all)]
  )
  p3 <-
    ggplot(note.draw, aes(x = Samtime, y = phenotype)) +
    geom_point(
      data = note.draw,
      shape = 21,
      size = 7.5,
      color = "red"
    ) +
    geom_text(
      label = note.draw$Quantity_of_capsule,
      color = "black",
      size = 4
    ) +
    geom_point(
      data = data.douching,
      aes(color = factor(Vaginal_douching_1M)),
      shape = 7,
      size = 4
    ) +
    geom_point(
      data = data.sex,
      aes(color = factor(Sexual_intercourse_24h)),
      shape = 17,
      size = 4
    ) +
    geom_point(
      data = data.med,
      aes(color = factor(Herbal_medicine_or_others_1M)),
      shape = 16,
      size = 4
    ) +
    geom_point(
      data = data.sen,
      aes(color = factor(Sensation_change)),
      size = 6,
      shape = 18
    ) +
    geom_point(
      data = data.ph,
      aes(color = factor(pH)),
      size = 4,
      shape = 15
    ) +
    geom_point(data = data.mens,      aes(color = factor(day_lmp_m)), size = 4) +
    geom_point(
      data = data.capsuletime,
      shape = 0,
      size = 7.5,
      color = "black"
    ) +
    geom_text(
      data = data.capsuletime,
      label = data.capsuletime$capsule_time ,
      color = "black",
      size = 3
    ) +
    labs(color = "") + xlab("") +
    scale_color_manual(values = cbPalette_v4, guide = guide_legend(ncol = 1)) +
    scale_y_discrete(limits = rev(
      c(
        "Quantity",
        "capsule_time/M",
        "Menstruation",
        "pH",
        "Sensation_change",
        "Herbal_medicine_or_others_1M",
        "Sexual_intercourse_24h",
        "Vaginal_douching_1M"
      )
    )) +
    theme_light() + theme(
      axis.title = element_blank(),
      axis.text.x = element_blank(),
      panel.background = element_rect(fill = "transparent", colour = NA),
      legend.background = element_rect(fill = "transparent", colour = NA),
      plot.background = element_rect(fill = "transparent", colour = NA)
    )
  ####
  ## HPV ##
  HPV.draw <-
    subset(data.hpv, SubjectID == samp.ID) %>% subset(RPKM_raw != 0) %>% subset(Sites %in% c("Vagina", "Feces"))
  HPV.draw <-
    merge(note.draw, HPV.draw, by = "Samtime", all = T) %>% subset(!is.na(Sites))
  HPV.draw$Sites <- relevel(HPV.draw$Sites, ref = "Vagina")
  
  p.HPV1 <-
    ggplot(subset(HPV.draw, Sites == "Vagina"),
           aes(x = Samtime, y = RPKM_raw, fill = HPV_type)) +
    geom_bar(stat = "identity", position = "stack") +
    scale_x_discrete(limits = levels(factor(note.draw$Samtime))) +
    scale_fill_manual(
      limits = levels(factor(HPV.draw$HPV_type)),
      values = cbPalette,
      guide = guide_legend(ncol = 1)
    ) +
    labs(fill = "HPV Types", size = 10) + xlab("") + ylab("RPKM") +
    theme_classic() + theme(
      axis.title.x = element_blank(),
      axis.text.x = element_blank(),
      axis.ticks = element_blank()
    )
  p.HPV2 <-
    ggplot(subset(HPV.draw, Sites == "Feces"),
           aes(x = Samtime, y = RPKM_raw, fill = HPV_type)) +
    geom_bar(stat = "identity", position = "stack") +
    scale_x_discrete(limits = levels(factor(note.draw$Samtime))) +
    scale_fill_manual(
      limits = levels(factor(HPV.draw$HPV_type)),
      values = cbPalette,
      guide = guide_legend(ncol = 1)
    ) +
    labs(fill = "HPV Types", size = 10) + xlab("") + ylab("RPKM") +
    theme_classic() + theme(
      axis.title.x = element_blank(),
      axis.text.x = element_blank(),
      axis.ticks = element_blank()
    )
  
  if (nrow(subset(HPV.draw, Sites == "Vagina")) != 0) {
    if (nrow(subset(HPV.draw, Sites == "Feces")) != 0) {
      ggsave(
        paste0(outdir, samp.ID, ".pdf"),
        plot = ggarrange(
          p1,
          p.HPV1,
          p.HPV2,
          p2,
          p3,
          ncol = 1,
          heights = c(3, 0.6, 0.6, 0.3, 1),
          align = "v",
          legend = "right",
          common.legend = FALSE
        ),
        #path = outdir,
        width = 12,
        height = 9
      )
    } else {
      ggsave(
        paste0(outdir, samp.ID, ".pdf"),
        plot = ggarrange(
          p1,
          p.HPV1,
          p2,
          p3,
          ncol = 1,
          heights = c(3, 0.6, 0.3, 1),
          align = "v",
          legend = "right",
          common.legend = FALSE
        ),
        #path = outdir,
        width = 12,
        height = 9
      )
    }
  } else{
    ggsave(
      paste0(outdir, samp.ID, ".pdf"),
      plot = ggarrange(
        p1,
        p2,
        p3,
        ncol = 1,
        heights = c(3, 0.2, 1),
        align = "v",
        legend = "right",
        common.legend = FALSE
      ),
      #path = outdir,
      width = 12,
      height = 9
    )
  }
  
}


```

```{r Lactobacillus.spp for SUBJECTS }
##  sFIG 6. Lactobacillus.spp FOR 4 SUBJECTS #####
prefix  <- "species"
phen.va <- phen %>% subset(Sites == "Vagina")
species.pro$tax <- rownames(species.pro)
dat <-
  melt(
    species.pro,
    id.vars = "tax" ,
    variable.name = "SeqID",
    value.name = "Abundance"
  )
dat <- merge(dat, phen.va, by = "SeqID", all.y = T)
#### all tax & order ##
dat.sites <- subset(dat, Sites == "Vagina")
tax.all   <-
  arrange(aggregate(dat.sites$Abundance, by = list(as.vector(
    factor(dat.sites$tax)
  )), mean), -x) %>% subset(x != 0)
cbPalette <-
  c(
    brewer.pal(8, "Set2"),
    brewer.pal(8, "Set1"),
    brewer.pal(8, "Set3"),
    brewer.pal(8, "Pastel2"),
    brewer.pal(8, "Pastel1"),
    colorRampPalette(c(
      "lightblue", "lightgreen", "lightpink", "grey60"
    ))(nrow(tax.all) - 40)
  )
###
sub.list <- c("S020", "S030", "S025", "S065")
##
dat.draw <- subset(dat.sites, SubjectID %in% sub.list)
dat.draw <- dat.draw[grep("Lactobacillus", dat.draw$tax), ]
dat.draw$Samtime    <- factor(as.vector(dat.draw$Samtime))
dat.draw$group_new <-
  factor(
    dat.draw$group_new,
    levels = c("B2", "B1", "B0", "O1", "O2", "O3", "O4", "O5", "O6",  "W1", "W2")
  )
####
tax.sum <-
  aggregate(dat.draw$Abundance,
            list(dat.draw$tax, dat.draw$SubjectID),
            max) %>% subset(x > 0)
dat.draw <- dat.draw %>%
  mutate(tax.sum.tag = paste(tax, SubjectID, sep = "_")) %>%
  subset(tax.sum.tag %in% paste(tax.sum$Group.1, tax.sum$Group.2, sep = "_"))
## COLOR ##
tax.draw <-
  arrange(aggregate(dat.draw$Abundance, by = list(as.vector(
    factor(dat.draw$tax)
  )), mean), -x) %>% subset(x != 0)
bPalette_p1 <- cbPalette[match(tax.draw, tax.all$Group.1)]
dat.draw$tax <- factor(dat.draw$tax, levels = tax.draw$Group.1)
dat.draw$SubjectID <- factor(dat.draw$SubjectID, levels = sub.list)
###
ggplot(dat.draw, aes(x = group_new, y = Abundance, color = tax)) +
  geom_point() +
  geom_line(aes(group = tax)) +
  labs(x = "", y = "Relative Abundance", color = "Taxa") +
  scale_color_manual(values = cbPalette_p1, guide = guide_legend(ncol = 1)) +
  facet_wrap( ~ SubjectID, scales = "free_x", ncol = 2) + theme_bw() + theme(strip.background = element_blank(), panel.grid = element_blank())
```